### PR TITLE
We have a backend!!

### PR DESCRIPTION
**Pull request by jesswils**
Get rid of the annoying express generator and replace with simple server and error handling

### CODE REVIEW

**Review by nolixul — APPROVED** [review]
Looks great :) I normally stick type: module in the package.json in front end projects, what issues could that bring up later?

**Comment by jesswils** [comment]
> Looks great :) I normally stick type: module in the package.json in front end projects, what issues could that bring up later?

Actually I was just told to not use it by le old manager when I was troubleshooting nextjs issues but a quick google shows that it’s not an issue. I’ll remove that from the readme but shall I use the type module over the file extension change?

**Comment by nolixul** [comment]
> > Looks great :) I normally stick type: module in the package.json in front end projects, what issues could that bring up later?
> 
> Actually I was just told to not use it by le old manager when I was troubleshooting nextjs issues but a quick google shows that it’s not an issue. I’ll remove that from the readme but shall I use the type module over the file extension change?

No it doesn't matter I think :) I was just curious, thanks for sharing!

Merge it when you're ready :D

**Comment by 321jellyfish** [comment]
Looks good 👍

**Pull request merged**
